version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - default
    ports:
      - 8080:8080
    environment:
      - APP_PORT=$APP_PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    volumes:
      - .:/app/
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3366:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - default
networks:
  default:
volumes:
  db_data: